name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Issue to JSON
        id: issue-to-json
        uses: ./
        with:
          issue-body: |
            <!-- Required parameters are marked with an asterisk (*) -->
            
            ### Foo *
            
            Hello, World!
            
            ### Bar
            
            Hello, Universe!
          template: example.md
          
      - name: Check Result
        env:
          RESULT: ${{ steps.issue-to-json.outputs.result }}
        run: |
          expected_result=$'{\n  "bar": "Hello, Universe!",\n  "foo": "Hello, World!"\n}'
          if [ "$RESULT" != "$expected_result" ]; then
            echo "Unexpected result: $RESULT"
            exit 1
          fi
